development:
  adapter: postgresql
  database: konacha_demo_development
  username:
  password:
  encoding: utf8
  min_messages: warning

test:
  adapter: postgresql
  database: konacha_demo_test
  username:
  password:
  encoding: utf8
  min_messages: warning
